{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: plotlylab
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  number: 0
  entry_points:
    - plotly-lab = plotlylab.labapp:main
    - plotly-labextension = plotlylab.labextensionapp:main

requirements:
  build:
    - python >=3
    - pip
    - nodejs
    - jupyterlab =0.35
  run:
    # ## Python packages corresponding to extensions installed in build.sh ##

    # plotly channel
    - plotly =3.7.0
    - plotly-orca
    - colorlover

    # main channel
    - ipywidgets >=7.2
    - jupyterlab =0.35
    - psutil
    - pandas
    - numpy
    - shapely
    - pyshp
    - geopandas
    - scipy
    - scikit-learn
    - scikit-image
    - pillow

    # dash (conda-forge channel)
    - dash
    - dash-core-components
    - dash-html-components
    - dash-table
    - dash-daq

    # R support (r channel)
    - r-irkernel
    - r-plotly
    - r-processx
    - openjdk

about:
  home: https://github.com/plotly/plotlylab
  license: MIT License
  license_file: LICENSE
  summary: A proof-of-concept JupyterLab distribution integrating Plotly technologies
