{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: plotlylab
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  entry_points:
    - plotly-lab = plotlylab.labapp:main
    - plotly-labextension = plotlylab.labextensionapp:main

requirements:
  build:
    - python >=3
    - pip
    - nodejs
    - jupyterlab =0.35
  run:
    # ## Python packages corresponding to extensions installed in build.sh ##
    # main channel
    - ipywidgets >=7.2
    - jupyterlab =0.35
    - psutil
    - pandas
    - numpy

    # plotly
    - plotly =3.7.1
    - jupyterlab-dash =0.1.0a2
    - plotly_express
    - plotly-orca
    - colorlover

    # dash
    - dash
    - dash-core-components
    - dash-html-components
    - dash-table
    - dash-daq

    # R support (r channel)
    - r-irkernel
    - r-plotly
    - r-processx
    - openjdk

about:
  home: https://github.com/plotly/plotlylab
  license: MIT
  license_file: LICENSE
  summary: A proof-of-concept JupyterLab distribution integrating Plotly technologies
