{% set name = "dash-html-components" %}
{% set version = "0.14.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/plotly/dash-html-components.git
  git_tag: "v{{ version }}"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - dash
    - pip
    - python
  run:
    - dash
    - python

test:
  imports:
    - dash_html_components

about:
  home: https://dash.plot.ly/dash-html-components
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dash UI HTML component suite
  doc_url: https://dash.plot.ly/dash-html-components
  dev_url: https://github.com/plotly/dash-html-components

extra:
  recipe-maintainers:
    - jonmmease
