{% set name = "dash-table" %}
{% set version = "3.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/plotly/dash-table.git
  git_tag: "v{{ version }}"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - dash
  run:
    - python
    - dash

test:
  imports:
    - dash_table

about:
  home: https://dash.plot.ly/datatable
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dash table
  doc_url: https://dash.plot.ly/datatable
  dev_url: https://github.com/plotly/dash-table

extra:
  recipe-maintainers:
    - jonmmease
