{% set name = "dash-renderer" %}
{% set version = "0.20.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/plotly/dash-renderer.git
  git_tag: "v{{ version }}"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - dash_renderer

about:
  home: https://github.com/plotly/dash-renderer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Front-end component renderer for dash
  doc_url:
  dev_url: https://github.com/plotly/dash-renderer

extra:
  recipe-maintainers:
    - jonmmease
