{% set name = "dash" %}
{% set version = "0.39.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/plotly/dash.git
  git_tag: "v{{ version }}"

build:
  number: 0
  noarch: python
  entry_points:
    - dash-generate-components = dash.development.component_generator:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - dash-renderer
    - flask >=0.12
    - flask-compress
    - pip
    - plotly
    - python
  run:
    - dash-renderer
    - flask >=0.12
    - flask-compress
    - plotly
    - python

test:
  imports:
    - dash
    - dash.development
  commands:
    - dash-generate-components --help

about:
  home: https://plot.ly/dash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python framework for building reactive web-apps. Developed by Plotly.
  doc_url: https://dash.plot.ly/
  dev_url: https://github.com/plotly/dash

extra:
  recipe-maintainers:
    - jonmmease
